### ISSUE TITLE
Создать сайт со списком школьников, где у каждого школьника есть личная страничка с его данными, статистиками.

### ISSUE THREAD

**Issue by JohnHook059** [SpyCheese/pesto-web#1]
Его данные: Имя, Фамилия.
Статистики: рейтинг языков, время на дорешке, любимая тема, % rejected'ов, "идеальность его кода".

Blocked by: #2 #3 #4 #5 #6

**Comment by kalinochkind** [comment]
Откуда брать возраст и пол?
