### ISSUE TITLE
Тулза для статистики дорешивания

### ISSUE THREAD

**Issue by SpyCheese** [SpyCheese/pesto-web#51]
Создать тулзу, которая заполняет статистику дорешивания в бае (добавить в модель).
Время дорешки за один день = (время последней посылки - время окончания обязательного решания).
Временем окончания обзательного решания можно считать обед (2 часа дня). Определять по timezone, который требуется добавить в смену.

**Comment by kalinochkind** [comment]
Статистика считается для каждого пользователя по всем сменам
