### ISSUE TITLE
Добавить рейтинг и статистику идеальности.

### ISSUE THREAD

**Issue by JohnHook059** [SpyCheese/pesto-web#6]
У каждого школьника должно быть поле, где указывается его идеальность.

Идеальность школьника = (кол-во задач, которые он сдал с 1-ой попытки / кол-во задач, которые он сдал всего)

**Comment by gurovic** [comment]
+

**Comment by JohnHook059** [comment]
@gurovic какой рейтинг?

**Comment by gurovic** [comment]
по идеальности
