### ISSUE TITLE
Сделать утилиту для преобразования имени из ejudge к виду ФамилияИмя

### ISSUE THREAD

**Issue by JohnHook059** [SpyCheese/pesto-web#61]
mysql> select username from users where user_id=8;
+------------------------------------------------------------------------------+
| username                                                                     |
+------------------------------------------------------------------------------+
| Ejudge (Канапин, Сукаев, Маркин)                                             |
| Гимназия 1543 (Гагкаева, Орехова, Макридина)                                 |
+------------------------------------------------------------------------------+
2 rows in set (0,00 sec)

mysql> select username from users where user_id=88;
+-----------------------------+
| username                    |
+-----------------------------+
| (M) Ионов Андрей            |
| (M) Ионов Андрей            |
+-----------------------------+
2 rows in set (0,04 sec)

mysql> select username from users where user_id=888;
+------------+
| username   |
+------------+
| mos-09-346 |
| mos-09-346 |
+------------+
2 rows in set (0,04 sec)

mysql> select username from users where user_id=8888;
+----------------------------------+
| username                         |
+----------------------------------+
| Меньшов Сергей - 10              |
| Меньшов Сергей - 10              |
+----------------------------------+
2 rows in set (0,04 sec)

mysql> select username from users where user_id=6676;
+------------+
| username   |
+------------+
| okrug-1914 |
| okrug-1914 |
| NULL       |
+------------+
3 rows in set (0,04 sec)

**Comment by gurovic** [comment]
это не нужно
